apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service-deployment
  labels:
    app: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        image: amarnathvenkatam/petclinic-vets-service:dev
        ports:
        - containerPort: 8083
---

apiVersion: v1
kind: Service
metadata:
  name: vets-service-service
spec:
  selector:
    app: vets-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
