apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service-deployment
  labels:
    app: visits-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
      - name: visits-service
        image: amarnathvenkatam/petclinic-visits-service:dev
        ports:
        - containerPort: 8082
---

apiVersion: v1
kind: Service
metadata:
  name: visits-service-service
spec:
  selector:
    app: visits-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
